application:
  base_url: "http://127.0.0.1"
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  # We are only setting the dev value
  # We will deal with the prod value outside oif version control
  # Given it is a sensitive secret!
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
